core/urls.py
from django.urls import path
from . import views


app_name = "core"

urlpatterns = [
    path('', views.legal_mentions, name="legal_mentions"),
]

favorites/urls.py
from django.urls import path
from . import views


app_name = "favorites"

urlpatterns = [
    path('add/', views.user_favorites_add, name="user_favorites_add"),
    path('delete/', views.user_favorites_delete, name="user_favorites_delete"),
    path('show/', views.show_favorites, name="show_favorites"),
]

products/urls.py
from django.urls import path
from . import views


app_name = "products"

urlpatterns = [
    path('', views.index, name="index"),
    path('products/', views.product_search, name="product_search"),
    path('products/autocomplete/', views.product_autocomplete, name="product_autocomplete"),
    path('products/<int:product_id>', views.details, name="product_details"),
]

purbeurre/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('products.urls', namespace="products")),
    path('admin/', admin.site.urls),
    # path('products/', include('products.urls')),
    path('favorites/', include('favorites.urls', namespace="favorites")),
    path('users/', include('users.urls')),
    path('legal/', include('core.urls'))
]

favorites/models.py
from django.db import models
from django.conf import settings

from .manager import FavoriteManager


class Favorite(models.Model):
    class Meta:
        unique_together = (('user', 'new_product', 'ancient_product'),)

    objects = FavoriteManager()

    date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    new_product = models.ForeignKey('products.Product', on_delete=models.CASCADE, related_name="new_product")
    ancient_product = models.ForeignKey('products.Product', on_delete=models.CASCADE, related_name="ancient_product")

favorites/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse

from .models import Favorite
from products.models import Product


def show_favorites(request):
    if request.user.is_authenticated:
        favorites = Favorite.objects.filter(user=request.user).order_by("-date")
        return render(request, "favorites/show_favorites.html", {"favorites": favorites})
    else:
        return redirect("users:user_login")


def user_favorites_add(request):
    if request.user.is_authenticated:
        if request.method == "POST":
            ancient_product_code = request.POST.get('old_product_code')
            new_product_code = request.POST.get('new_product_code')

            ancient_product = Product.objects.get(code=ancient_product_code)
            new_product = Product.objects.get(code=new_product_code)

            Favorite.objects.get_or_create(ancient_product=ancient_product,
                                           new_product=new_product,
                                           user=request.user)

    return JsonResponse({"key": "value"})


def user_favorites_delete(request):
    if request.user.is_authenticated:
        if request.method == "POST":
            ancient_product_code = request.POST.get('old_product_code')
            new_product_code = request.POST.get('new_product_code')

            ancient_product = Product.objects.get(code=ancient_product_code)
            new_product = Product.objects.get(code=new_product_code)

            try:
                Favorite.objects.get(user=request.user, ancient_product=ancient_product,
                                     new_product=new_product).delete()
            except Favorite.DoesNotExist:
                pass

    return JsonResponse({"key": "value"})

favorites/templates/favorites/fav_button.html
{% if user.is_authenticated %}
  <script>
    function addFavorite(old_code, new_code) {
        $.post("{% url "favorites:user_favorites_add" %}",
            {old_product_code: old_code, new_product_code: new_code}, function(data) {
          console.log("fav added !");
            });
    }

    function deleteFavorite(old_code, new_code) {
        $.post("{% url "favorites:user_favorites_delete" %}",
            {old_product_code: old_code, new_product_code: new_code}, function(data) {
              console.log("fav removed !");
            });
    }

  function onClickHandler(e) {
    const old_code = e.target.getAttribute("data-old-code");
    const new_code = e.target.getAttribute("data-code");

    if (e.target.classList.contains("add-fav")) {
        addFavorite(old_code, new_code);
    }
    else {
        deleteFavorite(old_code, new_code);
    }

    const classes_btn = ["add-fav", "remove-fav", "btn-success", "btn-danger"];
    for (let cls of classes_btn) {
        e.target.classList.toggle(cls);
      }

    const classes_fa = ["fa-heart", "fa-trash-alt"];
    let iElt = e.target.children[0];
    for (let fontClass of classes_fa) {
        iElt.classList.toggle(fontClass);
    }
  }
  </script>
{% endif %}

favorites/templates/favorites/show_favorites.html
{% extends "core/base.html" %}
{% load static %}

{% block title %}Vos Favoris{% endblock %}
{% block product_name %}Vos Favoris{% endblock %}

{% block content %}
  <div class="container">
    <div class="row">
      {% for favorite in favorites %}
        <div class="col-md-4 product-display">
          <a href="{% url "products:product_details" product_id=favorite.new_product.code %}">
            <img src="{{ favorite.new_product.image_url }}" alt="Image du produit" class="product-img" width=100 />
            <img src="{% static "core/img/nutriscore/"|add:favorite.new_product.nutriscore_img %}" class="nutriscore-img" alt="Nutriscore"/>
            <h3>{{ favorite.new_product.name|truncatechars:36 }}</h3></a>
            <a href="{% url "products:product_details" product_id=favorite.ancient_product.code %}">{{ favorite.ancient_product.name|truncatechars:35 }}
            <img src="{% static "core/img/nutriscore/"|add:favorite.ancient_product.nutriscore_img %}" class="favorite-nutriscore-img" alt="Nutriscore"/></a>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}