core/urls.py
from django.urls import path
from . import views


app_name = "core"

urlpatterns = [
    path('', views.legal_mentions, name="legal_mentions"),
]

favorites/urls.py
from django.urls import path
from . import views


app_name = "favorites"

urlpatterns = [
    path('add/', views.user_favorites_add, name="user_favorites_add"),
    path('delete/', views.user_favorites_delete, name="user_favorites_delete"),
    path('show/', views.show_favorites, name="show_favorites"),
]

products/urls.py
from django.urls import path
from . import views


app_name = "products"

urlpatterns = [
    path('', views.index, name="index"),
    path('products/', views.product_search, name="product_search"),
    path('products/autocomplete/', views.product_autocomplete, name="product_autocomplete"),
    path('products/<int:product_id>', views.details, name="product_details"),
]

purbeurre/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('products.urls', namespace="products")),
    path('admin/', admin.site.urls),
    # path('products/', include('products.urls')),
    path('favorites/', include('favorites.urls', namespace="favorites")),
    path('users/', include('users.urls')),
    path('legal/', include('core.urls'))
]

users/urls.py
from django.urls import path
from . import views


app_name = "users"

urlpatterns = [
    path('', views.index, name="index"),
    path('new/', views.create_new_user, name="user_registration"),
    path('new/add/', views.add_new_user, name="user_add"),
    path('login/', views.user_login, name="user_login"),
    path('login/check/', views.user_check_login, name="user_check_login"),
    path('logout/', views.user_logout, name="user_logout"),
    path('account/', views.user_account, name="user_account"),
]

core/views.py
from django.shortcuts import render


def legal_mentions(request):
    return render(request, "core/credits.html")

core/templates/core/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
{% block head %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Pur Beurre - {% block title %}Trouvez des produits sains{% endblock %}</title>

  <!-- Font Awesome Icons -->
{#  <link href='{% static "core/vendor/fontawesome-free/css/all.min.css" %}' rel="stylesheet" type="text/css">#}
  <script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js" crossorigin="anonymous"></script>

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
  <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
  <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Scope+One" rel="stylesheet" type="text/css">

  <!-- Plugin CSS -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css" rel="stylesheet" />
  <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

  <!-- Theme CSS - Includes Bootstrap -->
{#  <link href='{% static "core/css/creative.min.css" %}' rel="stylesheet">#}
  <link href='{% static "dist/css/styles.css" %}' rel="stylesheet" />

  <!-- Favicon -->
  <link rel="shortcut icon" href="{% static 'core/img/logo_pur_beurre-favicon.png' %}">
{% endblock %}
</head>

<body class="d-flex flex-column min-vh-100 justify-content-between" id="page-top">

{% block navbar %}
 {% include "core/navbar_search.html" %}
{% endblock %}

{% block picture_product %}
  <!-- Call to Action Section -->
  <section class="page-section bg-gradient text-white">
    <div class="container text-center">
      <h2 class="mb-4">{% block product_name %}{% endblock %}</h2>
{#      <a class="btn btn-light btn-xl" href="https://startbootstrap.com/themes/creative/">Download Now!</a>#}
    </div>
  </section>
{% endblock %}


{% block content %}{% endblock %}


{% block footer %}
  <!-- Footer -->
  <footer class="bg-light py-5 mt-3">
    <div class="container">
{#      <div class="col-lg-4 small text-center text-muted">Copyright &copy; 2019 - Start Bootstrap</div>#}
      <div class="row">
        <div class="col-lg-6 small text-center text-muted">
          <a href="{% url 'core:legal_mentions' %}">Mentions légales</a>
        </div>
        <div class="col-lg-6 small text-center text-muted">
          <a href="mailto:direct@danslesspams.com">Contact</a>
        </div>
      </div>
    </div>
  </footer>
{% endblock %}

{% block script %}
  <!-- Bootstrap core JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script>

  <!-- Plugin JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>
  <!-- Custom scripts for this template -->
{#  <script src='{% static "core/js/creative.min.js" %}'></script>#}

  <script src='{% static "core/js/jquery-ui.min.js" %}'></script>
  <script src='{% static "src/js/scripts.js" %}'></script>
  
  <script type="text/javascript">$(".search-form").autocomplete({
    source: "{% url 'products:product_autocomplete' %}",
    minLength: 3
  });
  </script>
  <script>{% include "core/csrftoken.js" %}</script>
{% endblock %}

</body>

</html>

core/templates/core/base_masthead.html
{% extends "core/base.html"%}

{% block picture_product %}{% endblock %}

{% block content %}
  {% block masthead %}
    <!-- Masthead -->
    <header class="masthead">
      <div class="container h-100">
        <div class="row h-100 align-items-center justify-content-center text-center">
          {% if messages %}
            {% for message in messages %}
              <div class="col-lg-10 align-self-end">
                <h4 class="text-white py-2 ctx-message">{{ message }}</h4>
                <hr class="divider my-4">
              </div>
            {% endfor %}
          {% endif %}
          <div class="col-lg-10 align-self-end">
            <h1 class="text-uppercase text-white font-weight-bold">{% block intro %}{% endblock %}</h1>
            <hr class="divider my-4">
          </div>
          <div class="col-lg-8 align-self-baseline">
            <h2 class="text-white-75 font-weight-light mb-5">{% block masthead_title %}{% endblock %}</h2>
  <!--          <a class="btn btn-primary btn-xl js-scroll-trigger" href="#about">Find Out More</a>-->

            {% block search %}{% endblock %}

          </div>
        </div>
      </div>
    </header>
  {% endblock %}
{% endblock %}

core/templates/core/credits.html
{% extends 'core/base.html' %}

{% block title %}Mentions légales{% endblock %}

{% block picture_product %}{% endblock %}

{% block content %}
  <section class="page-section bg-gradient" id="about">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-8 text-center">
          <h2 class="text-white mt-0">Mentions légales</h2>
        </div>
      </div>
    </div>
  </section>

  <section class="page-section" id="credit-list">
    <div class="container">
      <h2 class="mb-4">Les ressources suivantes ont été utilisées :</h2>
      <ul>
        <li class="credit-text">Template <a href="https://github.com/BlackrockDigital/startbootstrap-creative">
          Bootstrap Creative
        </a></li>
        <li class="credit-text">Icônes <a href="https://fontawesome.com/">Font Awesome</a></li>
        <li class="credit-text">Photos de Colette et Rémy - <a href="https://www.pixar.com/">Pixar</a></li>
        <li class="credit-text">Autre Photo - <a href="https://unsplash.com/photos/eqsEZNCm4-c">Olenka Kotyk</a></li>
        <li class="credit-text">Projet <a href="https://openclassrooms.com/">OpenClassRooms</a></li>
      </ul>
    </div>
  </section>
{% endblock %}

core/templates/core/home.html
{% extends "core/base_masthead.html" %}

{% block content %}
  {{ block.super }}

  {% block story %}
    <!-- About Section -->
    <section class="page-section bg-primary" id="about">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-8 text-center">
            <h2 class="text-white mt-0">Colette et Rémy</h2>
            <hr class="divider light my-4">
            <p class="text-white-50 mb-4">Colette Tatou : "Nous aimons tous manger, surtout en France ! Personnellement, une baguette fraîche, du bon fromage de chèvre et un bon vin rouge me suffisent amplement. Comme tout le monde, je fais mes courses au supermarché. Mais petit à petit je me suis rendue compte, surtout lorsque nous avons ouvert le restaurant, que je pouvais remplacer les produits aseptisés que j'avais l'habitude d'acheter par de bons produits du terroir Et souvent pour le même prix !"</p>
            {% load static %}
            <img class="portrait-col" src="{% static 'core/img/portraits/colette-tatou-full.png' %}">
            <img class="portrait-rat" src="{% static 'core/img/portraits/remy-nobg.png' %}">
          </div>
        </div>
      </div>
    </section>
  {% endblock %}

  {% block contact %}
    <!-- Contact Section -->
    <section class="page-section" id="contact">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-8 text-center">
            <h2 class="mt-0">Contactez-nous !</h2>
            <hr class="divider my-4">
            <p class="text-muted mb-5">Notre équipe est à votre écoute 24 heures sur 24 !</p>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-4 ml-auto text-center mb-5 mb-lg-0">
            <i class="fas fa-phone fa-3x mb-3 text-muted"></i>
            <div>01 02 03 04 05</div>
          </div>
          <div class="col-lg-4 mr-auto text-center">
            <i class="fas fa-envelope fa-3x mb-3 text-muted"></i>
            <!-- Make sure to change the email address in anchor text AND the link below! -->
            <a class="d-block" href="mailto:direct@danslesspams.com">support@purbeurre.com</a>
          </div>
        </div>
      </div>
    </section>
  {% endblock %}

{% endblock %}

core/templates/core/navbar.html
{% load static %}
<!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
    <div class="container">
      <a class="navbar-brand js-scroll-trigger" href="{% url "products:index" %}">
        <img src="{% static "core/img/logo_pur_beurre.png" %}" class="logo-purbeurre" alt="Logo PurBeurre"/> Pur Beurre</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">

        <ul class="navbar-nav ml-auto my-2 my-lg-0">
          {% block navsearch %}
          {% endblock %}
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger mt-1 ml-2" href="{% url "users:user_account" %}">
              <i class="fas fa-user" aria-hidden="true"></i><span class="ml-2 burger-menu">Votre profil</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger mt-1" href={% url "favorites:show_favorites" %}>
              <i class="fas fa-carrot" aria-hidden="true"></i><span class="ml-2 burger-menu">Vos favoris</span></a>
          </li>
          <li class="nav-item">
            {% if user.is_authenticated %}
              <a class="nav-link js-scroll-trigger mt-1" href="{% url "users:user_logout" %}">
                <i class="fas fa-sign-out-alt" aria-hidden="true"></i><span class="ml-2 burger-menu">Se déconnecter</span>
            {% else %}
              <a class="nav-link js-scroll-trigger mt-1" href="{% url "users:user_login" %}">
                <i class="fas fa-sign-in-alt" aria-hidden="true"></i><span class="ml-2 burger-menu">Se connecter</span>
            {% endif %}
            </a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

core/templates/core/navbar_search.html
{% extends "core/navbar.html" %}

{% block navsearch %}
  <li class="nav-item">
    <form action="{% url 'products:product_search' %}" method="get" class="search-form">
      {{ form.as_p }}
    </form>
  </li>
{% endblock %}