core/urls.py
from django.urls import path
from . import views


app_name = "core"

urlpatterns = [
    path('', views.legal_mentions, name="legal_mentions"),
]

purbeurre/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('products.urls', namespace="products")),
    path('admin/', admin.site.urls),
    # path('products/', include('products.urls')),
    path('favorites/', include('favorites.urls', namespace="favorites")),
    path('users/', include('users.urls')),
    path('legal/', include('core.urls'))
]

users/urls.py
from django.urls import path
from . import views


app_name = "users"

urlpatterns = [
    path('', views.index, name="index"),
    path('new/', views.create_new_user, name="user_registration"),
    path('new/add/', views.add_new_user, name="user_add"),
    path('login/', views.user_login, name="user_login"),
    path('login/check/', views.user_check_login, name="user_check_login"),
    path('logout/', views.user_logout, name="user_logout"),
    path('account/', views.user_account, name="user_account"),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin

from users.manager import UserManager


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField("email address", unique=True)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

users/forms.py
from django import forms


class UserForm(forms.Form):
    email = forms.EmailField(label="Votre email", required=True)
    password = forms.CharField(label="Votre mot de passe", max_length=128,
                               required=True, widget=forms.PasswordInput(attrs={"class": "password-field"}))

users/views.py
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse
from django.contrib.auth import logout, login, authenticate
from django.contrib import messages
from django.db.utils import IntegrityError

from .forms import UserForm
from .models import User
from products.forms import SearchForm


def index(request):
    if request.user.is_authenticated:
        return redirect(reverse("users:user_account"))
    else:
        return redirect("users:user_registration")


def user_login(request):
    user_form = UserForm(request.GET or None)
    form = SearchForm(request.GET or None)
    return render(request, 'users/login.html', {'user_form': user_form, 'form': form})


def user_logout(request):
    logout(request)

    return redirect("products:index")


def user_check_login(request):
    form = UserForm(request.GET or None)

    if form.is_valid():
        user_mail = form.cleaned_data['email']
        user_password = form.cleaned_data['password']

        user = authenticate(email=user_mail, password=user_password)

        if user:
            login(request, user)
        else:
            messages.add_message(request, messages.INFO, "Nom d'utilisateur ou mot de passe "
                                                         "incorrect.")
            return redirect("users:user_login")

    return redirect(reverse("products:index"))


def create_new_user(request):
    user_form = UserForm(request.GET or None)
    form = SearchForm(request.GET or None)

    return render(request, "users/registration.html", {'form': form, 'user_form': user_form})


def add_new_user(request):
    form = UserForm(request.POST or None)

    if form.is_valid():
        user_mail = form.cleaned_data['email']
        user_password = form.cleaned_data['password']

        try:
            user = User.objects.create_user(email=user_mail, password=user_password)
            return redirect("users:user_login")
        except IntegrityError as e:
            messages.add_message(request, messages.INFO, "Cet email a déjà un compte.")

    return redirect("users:user_registration")


def user_account(request):
    if request.user.is_authenticated:
        return render(request, "users/account.html")

    return redirect("users:user_login")

users/templates/users/account.html
{% extends 'core/base.html' %}

{% block picture_product %}{% endblock %}

{% block title %}Informations du compte{% endblock %}

{% block content %}
  <section class="page-section bg-gradient" id="about">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-8 text-center">
          <h2 class="text-white mt-0">Votre adresse email : {{ user.email }}</h2>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

users/templates/users/login.html
{% extends "core/base_masthead.html" %}

{% block title %}Se connecter{% endblock %}
{% block intro %}Connexion{% endblock %}

{% block search %}
  <form action="{% url 'users:user_check_login' %}" method="get" class="form-login">
    {{ user_form.as_p }}
    <input class="btn btn-light btn-xl" type="submit" value="Se connecter"/>
  </form>
  <a class="btn btn-light btn-xl mt-2" href="{% url 'users:user_registration' %}">Créer un compte</a>
{% endblock %}

users/templates/users/registration.html
{% extends "core/base_masthead.html" %}

{% block title %}Création de compte{% endblock %}
{% block intro %}Créez votre compte{% endblock %}

{% block search %}
  <form action="{% url 'users:user_add' %}" method="post" class="form-registration">
    {% csrf_token %}
    {{ user_form.as_p }}
    <input class="btn btn-light btn-xl" type="submit" value="OK"/>
  </form>
{% endblock %}